name: first
on: push
jobs:
    job1:
        name: first job
        runs-on: ubuntu-latest
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: env | sort

    job2:
        name: sec job
        runs-on: window-latest
        steps:
        - name: step one
          uses: actions/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env: | Sort-Object Name"